### ISSUE TITLE
Generic formulations are not generated

### ISSUE THREAD

**Issue by christophertubbs** [NOAA-OWP/ngen#184] opened 2020-10-13 15:58 UTC
If a formulation for a catchment hasn't been defined, it should be derived from the global configuration.

## Current behavior

The driver just parses the configuration and assumes it has a member for every catchment

## Expected behavior

The driver should be including the hydrofabric so that every location has a formulation by assigning global formulations to locations without an explicit configuration.

**Comment by hellkite500** [comment] 2020-10-13 16:12
Duplicate of #166

**Comment by christophertubbs** [comment] 2020-10-14 18:08
This isn't really a dupe - this is just the issue of unconfigured formulations not being created. The scope here is a bit smaller than the scope in #166

**Closed** 2020-10-16 16:19 UTC
Labels: bug
