### ISSUE TITLE
NetCDF forcing provider time shift issue

### ISSUE THREAD

**Issue by jduckerOWP** [NOAA-OWP/ngen#450] opened 2022-10-03 20:15 UTC
NextGen user should be able to provide a netcdf forcings file and run NextGen starting at any point within the provided netcdf timeseries. Currently, NextGen netCDF forcings provider does not properly extract meteorological forcings for the NextGen simulation if the realization configuration start time does not match the netcdf start time. 

## Current behavior
When the user specifies a different start time within the realization configuration file than the start time of the netcdf forcing file, the NextGen netcdf provider (ngen/include/forcing/NetCDFPerFeatureDataProvider.hpp) will not properly find the correct timestep for the meteorological forcings that is specified in the realization configuration file. Instead, the forcings will be shifted in time based on the time discrepancy between the start of the netcdf file (e.g. 2007/01/01) and the realization configuration file (e.g. 2007/10/01, 9 month offset). 

## Expected behavior
The NextGen netcdf provider should be able to slice the netcdf file indices based on the "Time" variable matching the user requested start time of the realization configuration file and properly extract the meteorological forcings indices for each NextGen timestep of the simulation from start time to stop time. 

## Steps to replicate behavior (include URLs)

1. Generate a netcdf file for a given NextGen simulation.
2. Edit the realization configuration file to start at any other time besides the start time of your netcdf file. Ex: netcdf timeseries (2007-01-01 00:00:00 to 2019-12-23 00:00:00), realization configuration start time: 2007-10-01 00:00:00, stop time: 2008-01-01 00:00:00.
3. Look in output diagnostic files and you will see the meteorological forcings in a timeseries will be shifted.

**Comment by mattw-nws** [comment] 2022-10-03 20:34
Wow. That's uncanny. Duplicate of the almost 100% simultaneously submitted #451 .

**Comment by mattw-nws** [comment] 2022-10-03 20:36
Duplicate of #451

**Closed by mattw-nws** 2022-10-03 20:36 UTC
