### ISSUE TITLE
NextGen not finding Python packages in virtual environments

### ISSUE THREAD

**Issue by peckhams** [NOAA-OWP/ngen#441] opened 2022-09-07 16:34 UTC
## Current behavior

After compiling NextGen on a Mac and successfully running all tests, NexGen is not finding Python packages/modules in active virtual environments (either conda or venv).  The error message is:  ModuleNotFoundError.  This appears to be an instance of a known problem when Python is embedded in an executable via pybind11, as described here:
https://stackoverflow.com/questions/56904149/embedding-python-with-pybind11-virtual-environment-doesnt-work
Another possible solution can be found here:
https://docs.python.org/3.11/library/sys_path_init.html#embedded-python
A work-around is to provide the paths to all Python packages using the environment variable PYTHONPATH.

## Expected behavior

NextGen should be able to find Python packages that have been installed in a virtual environment when it is run with that environment active.  It should not be necessary to set PYTHONPATH.  It should also not be necessary to first install the package in a virtual environment and then compile NextGen with that environment active.

## Setup for the tests

0.  Install NextGen by following these online docs:
    https://noaa-owp.github.io/ngen/index.html
    https://noaa-owp.github.io/ngen/md_doc__d_e_p_e_n_d_e_n_c_i_e_s.html
    https://noaa-owp.github.io/ngen/md__i_n_s_t_a_l_l.html
    https://noaa-owp.github.io/ngen/md_doc__b_u_i_l_d_s__a_n_d__c_m_a_k_e.html
    https://noaa-owp.github.io/ngen/md_doc__b_m_i__m_o_d_e_l_s.html
    Also see the "Install ngen" section of this Google doc:
    https://docs.google.com/document/d/17e6HZtSx9Wn6QHnYaLhoHcaCpwrj0rJ3bTh40lbriBQ/edit#heading=h.lzjs5neq2b50

1.  There is a test project folder called "bmi-python-module" that contains a Python
    package folder called "bmihydro", that contains a BMI model source code module
    called "toybmi" (i.e. toybmi.py) that defines a class called "toybmi".
    Copy it into the folder:  ngen/extern/
    (Note that the tests give the same result with the new LSTM Python package.)

2.  Make sure bmihydro is not installed in the conda base environment:
       (base) % pip list
    If it is, uninstall it with:
       (base) % pip uninstall bmihydro

3.  Check whether the environment variable PYTHONPATH has been set:
       (base) % echo $PYTHONPATH
    If it has, this path will be prepended to Python's "sys.path", which will affect
    the tests.  You can unset this environment variable (which only applies to the
    active terminal window) with:
       (base) % export PYTHONPATH=''

4.  In order to run the toybmi model via NextGen, 3 input files are required, namely
       - a "catchment data file" (geojson)
       - a "nexus data file" (geojson) and
       - a "toybmi realization config" file (json).
    Starting from catchment data and nexus data files for all HUC01 catchments:
        catchment_data.geojson and
        nexus_data.geojson
    found in the Lynker AWS S3 bucket at: Amazon S3 > Buckets > formulations-dev > HUC01,
    all records were removed except those for "cat-67" and its nexus "nex-65", to create
    the much smaller files: catchment_data_cat67.geojson and nexus_data_nex65.geojson.
    Using these smaller files speeds up the testing process.
    A "realization config" file for the toybmi model is available at:
        ngen/extern/bmi-python-module/toybmi_realization.json
    All 3 of these files were copied into the ngen/data folder.
    The realization config file for toybmi then required editing the "init_config" path.

5.  Optional.  In ngen/extern/bmi-python-module/bmihydro, added 2 files:
       - \_\_main\_\_.py'''
       - run_toybmi_with_bmi.py
    These allow the model to be run via:
       % cd path-to-ngen-project-folder
       % python -m bmihydro

## Steps to reproduce with venv

1.  The ngen project folder contains a folder, ngen/venv, with a virtual environment.
    First, activate this environment:
    (base) % cd ngen
    (base) % source venv/bin/activate
    (venv) (base) % which pip
       /Users/peckhams/Dropbox/GitHub/ngen/venv/bin/pip
    (venv) (base) % pip list
    (venv) (base) % cd extern/bmi-python-module
    (venv) (base) % pip install -e .    (uses setup.py)
    (venv) (base) % pip list
    (venv) (base) % cd ../..
    (venv) (base) % python
       \>\>\> import bmihydro
       \>\>\> from bmihydro import toybmi
       \>\>\> import sys
       \>\>\> sys.path
       ['', '/Applications/anaconda3/lib/python37.zip', '/Applications/anaconda3/lib/python3.7', '/Applications/anaconda3/lib/python3.7/lib-dynload', '/Users/peckhams/Dropbox/GitHub/ngen/venv/lib/python3.7/site-packages', '/Users/peckhams/Dropbox/GitHub/ngen/extern/t-route/src/ngen_routing/src', '/Users/peckhams/Dropbox/GitHub/ngen/extern/t-route/src/nwm_routing/src', '/Users/peckhams/Dropbox/GitHub/ngen/extern/lstm_py']

NOTE:  In this list, there is no:
       '/Users/peckhams/Dropbox/GitHub/ngen/extern/bmihydro'
       For some reason, it was instead installed at:
        '/Users/peckhams/Dropbox/GitHub/ngen/venv/lib/python3.7/site-packages/bmihydro-0.0.1.dist-info'

2.  (venv) (base) % python -m bmihydro   # Requires optional Step (5) in Setup section.
        (Model runs successfully but doesn't use any of the JSON files.)

3.  (venv) (base) % ./cmake_build/ngen ./data/catchment_data_cat67.geojson "cat-67" ./data/nexus_data_nex65.geojson "nex-65" ./data/toybmi_realization.json

   ####  NextGen Console Output  ####
   NGen Framework 0.1.0
   Building Nexus collection
   Building Catchment collection
   libc++abi.dylib: terminating with uncaught exception of type std::runtime_error:
     ModuleNotFoundError: No module named 'bmihydro'
   zsh: abort      ./cmake_build/ngen ./data/catchment_data_lstm_test.geojson "cat-67"  "nex-65"

## Steps to reproduce with conda environment

1.  Deactivate venv, if necessary:
    (venv) (base) % deactivate

2.  Create a virtual environment called: toybmi_test, activate it, etc.:
    (base) % conda create --name toybmi_test
    (toybmi_test) % conda activate toybmi_test
    (toybmi_test) % cd ngen
    (toybmi_test) % which pip
       pip not found
    (toybmi_test) % conda install pip pyyaml
    (toybmi_test) % which pip
       /Applications/anaconda3/envs/toybmi_test/bin/pip
    (toybmi_test) % pip list
    (toybmi_test) % cd extern/bmi-python-module
    (toybmi_test) % pip install -e .    (uses setup.py)
    (toybmi_test) % pip list
    (toybmi_test) % cd ../..
    (toybmi_test) % python
       \>\>\> import bmihydro
       \>\>\> from bmihydro import toybmi
       \>\>\> import sys
       \>\>\> sys.path
       ['', '/Applications/anaconda3/envs/toybmi_test/lib/python310.zip', '/Applications/anaconda3/envs/toybmi_test/lib/python3.10', '/Applications/anaconda3/envs/toybmi_test/lib/python3.10/lib-dynload', '/Applications/anaconda3/envs/toybmi_test/lib/python3.10/site-packages', '/Applications/anaconda3/envs/toybmi_test/lib/python3.10/site-packages/PyYAML-6.0-py3.10-macosx-10.9-x86_64.egg']

3.  (toybmi_test) % python -m bmihydro     # Requires optional Step (5) in Setup section.
        (Model runs successfully but doesn't use any of the JSON files.)

4.  (toybmi_test) % ./cmake_build/ngen ./data/catchment_data_cat67.geojson "cat-67" ./data/nexus_data_nex65.geojson "nex-65" ./data/toybmi_realization.json

   ####  NextGen Console Output  ####
   NGen Framework 0.1.0
   Building Nexus collection
   Building Catchment collection
   libc++abi.dylib: terminating with uncaught exception of type std::runtime_error:
     ModuleNotFoundError: No module named 'bmihydro'
   zsh: abort      ./cmake_build/ngen ./data/catchment_data_lstm_test.geojson "cat-67"  "nex-65"

## Work-around by setting PYTHONPATH

1.  Set the PYTHONPATH environment variable:
     (venv) (base) % export PYTHONPATH='/Users/peckhams/Dropbox/GitHub/ngen/extern/bmi-python-module'

2.  (venv) (base) % echo $PYTHONPATH
          /Users/peckhams/Dropbox/GitHub/ngen/extern/bmi-python-module

3.  OPTIONAL:  Comment out the line in bmihydro/\_\_init\_\_.py:
         from .toybmi import toybmi
     This line imports the class "toybmi" from the module "toybmi", making the module itself
     (corresponding to toybmi.py), and any other classes or functions within it, unaccessible.
     Next, in the file:  ngen/data/toybmi_realization.json,
     change "bmihydro.toybmi" to "bmihydro.toybmi.toybmi".

4.  (venv) (base) % python
     \>\>\> import sys
     \>\>\> sys.path    (notice first entry is PYTHONPATH)
     \>\>\> from bmihydro import toybmi
     \>\>\> toy = toybmi.toybmi()   (if you did step 3)
     \>\>\> toy = toybmi()  (if you didn't do step 3)

5.  (venv) (base) % cd ngen

6.   (venv) (base) % ./cmake_build/ngen ./data/catchment_data_cat67.geojson "cat-67" ./data/nexus_data_nex65.geojson "nex-65" ./data/toybmi_realization.json

#### NextGen Console Output (with or without doing step (3)) ####
NGen Framework 0.1.0
Building Nexus collection
Building Catchment collection
Catchment topology is dendridic.
Running Models
Running timestep 0
Definition of "au" in "/Users/peckhams/Dropbox/GitHub/ngen/cmake_build/UDUNITS-2/build/share/udunits/udunits2-accepted.xml", line 123, overrides prefixed-unit "1.6605402e-45 kilogram"
Definition of "kt" in "/Users/peckhams/Dropbox/GitHub/ngen/cmake_build/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 105, overrides prefixed-unit "1000000 kilogram"
Definition of "microns" in "/Users/peckhams/Dropbox/GitHub/ngen/cmake_build/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 416, overrides prefixed-unit "1e-15 second"
Definition of "ft" in "/Users/peckhams/Dropbox/GitHub/ngen/cmake_build/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 527, overrides prefixed-unit "1e-12 kilogram"
Definition of "yd" in "/Users/peckhams/Dropbox/GitHub/ngen/cmake_build/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 536, overrides prefixed-unit "8.64e-20 second"
Definition of "pt" in "/Users/peckhams/Dropbox/GitHub/ngen/cmake_build/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 790, overrides prefixed-unit "1e-09 kilogram"
Definition of "at" in "/Users/peckhams/Dropbox/GitHub/ngen/cmake_build/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 1259, overrides prefixed-unit "1e-15 kilogram"
Definition of "ph" in "/Users/peckhams/Dropbox/GitHub/ngen/cmake_build/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 1889, overrides prefixed-unit "3.6e-09 second"
Definition of "nt" in "/Users/peckhams/Dropbox/GitHub/ngen/cmake_build/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 1898, overrides prefixed-unit "1e-06 kilogram"
Running timestep 100
Running timestep 200
Running timestep 300
Running timestep 400
Running timestep 500
Running timestep 600
Running timestep 700
Finished 720 timesteps.

**Comment by peckhams** [comment] 2022-09-07 16:41
## Notes regarding venv:

1.  venv is included in the Python standard library (Python 3.3 and above).
2.  The NextGen project has a folder:  ngen/venv with the virtual environment.
3.  To create a new venv environment:
     % python3 -m venv /path/to/new/virtual/environment
4.  To activate a venv from ngen folder:
     % source venv/bin/activate
5.  To deactivate an active venv from any folder:
     (myenv) % deactivate
6.  To install pip in an active venv:
     % python -m ensurepip --upgrade 
     (See: https://pip.pypa.io/en/stable/installation/)
     However, pip is installed in a new venv by default since Python 3.4.
7.  To list packages in an active venv (installed with pip):
     (myenv) % pip list
8.  To install a package in an active venv environment:
     (myenv) % cd project_dir  (which has setup.py)
     (myenv) % pip install -e .
9.  To uninstall a package in an active venv environment:
     (myenv) % pip uninstall package_name
10.  To view documentation for venv:
     https://docs.python.org/3/library/venv.html
11.  The files associated with a venv virtual environment are often placed
     in a folder called .venv or venv, within a project folder (like ngen).
     The files associated with a conda virtual environment are by default
     placed in a central place (e.g. /Applications/anaconda3/envs/) and each
     environment has a unique name.  (Try: % conda env list)

**Comment by peckhams** [comment] 2022-09-07 16:44
## Notes regarding conda

1.  If you have an Anaconda Python distribution, conda will be available.
2.  To create a new conda environment:
     % conda create --name myenv
3.  To activate a conda environment:
     % conda activate myenv
4.  To deactivate a conda environment:
     (myenv) % conda deactivate
5.  To install pip in an active conda environment:
     (myenv) % which pip   (check for another pip)
     (myenv) % conda install pip
     (myenv) % which pip
     *** This is important in order for paths to be set correctly. ***
6.  To list packages in an active conda environment:
     (myenv) % conda list
     (myenv) % pip list
7.  To install a package in an active conda environment:
     (myenv) % cd project_dir (which has setup.py)
     (myenv) % pip install -e .
8.  To uninstall a package in an active conda environment:
     (myenv) % pip uninstall package_name
9.  To view documentation for conda:
     https://docs.conda.io/en/latest/
10.  The files associated with a conda virtual environment are placed in
     a central place (e.g. /Applications/anaconda3/envs/) by default and
     each environment has a unique name.  The files associated with a venv
     virtual environment are often placed in a folder called .venv or venv,
     within a project folder (like ngen).
11.  The so-called conda "base" environment is typically auto-activated.
     Auto-activation can be disabled (e.g. for testing) with:
     (base) % conda config --set auto_activate_base false
     Auto-activation can be enabled similarly with:
     % conda config --set auto_activate_base true
12.  To view all past revisions of any conda environment:
     % conda activate myenv
     % conda list --revisions

**Comment by peckhams** [comment] 2022-09-07 16:45
## Notes regarding pip

1.  pip is the preferred installer program for Python and has been
    included with the Python binary installers since Python 3.4.
    pip will usually be available in the base conda environment,
    however, you should use a pip installed in your virtual enviroment
    in order for sys.path to be updated correctly.
2.  To check which pip instance will be used:
    % which pip
3.  To check your version of pip:
    % pip --version   (OR)
    % python -m pip --version
4.  To update to latest version of pip:
    % pip install --upgrade pip (OR)
    % python -m pip install --upgrade pip
5.  To list packages in an active virtual environment:
    % pip list
6.  To install a package from Python Package Index (pypi.org):
    % python -m pip install project_name
7.  To install your own package in an active virtual environment:
    % cd project_dir (which has setup.py)
    % pip install -e .   (in editable/developer mode)
8.  To show information for a package:
    % pip show package_name (OR)
    % python -m pip show package_name
9.  To uninstall a package in an active virtual environment:
    % pip uninstall package_name. (OR)
    % python -m pip uninstall package_name
10.  To view documentation for pip:
     https://pip.pypa.io/en/stable/getting-started/

**Comment by hellkite500** [comment] 2022-10-26 19:25
Does this issue exist if you don't install egg links (e.g. `-e` in `pip install`)?  I've found this issue on MacOS in the past, and pybind on macos doesn't seem to be able to use egg links correctly.

**Comment by hellkite500** [comment] 2022-10-26 19:27
Also, has this been verified as an issue on other operating systems?

**Comment by hellkite500** [comment] 2022-10-26 19:53
>After compiling NextGen
Can you also provide any CMake output from this step? This may be helpful in understanding what the python environment CMake provides to pybind and the ngen build.

**Comment by mattw-nws** [comment] 2022-11-17 16:27
@peckhams I've been keeping this and related issues in mind, one result of which is #476 which was just merged. Could you pull a copy of the latest master branch and run ngen _with no arguments_ in some of the environments that are troublesome? This will show you the version of the embedded Python interpreter and the system paths that are in use.

Notably, two things about the way ngen works with Python that I now understand better after implementing that PR#476:

1. ngen actually already does what you suggest (explicitly adds things to `sys.path`) when it finds the `VIRTUAL_ENV` variable set. This is set by a venv's `activate` script... so why this wouldn't be working as expected is a mystery. The output provided by the PR may shed some light on this.
2. ngen _also_ hunts for an includes paths from venv directories named `venv` or `.venv` in the current directory or one or two directories above--the first one it finds. This is probably behavior we should eliminate because it could easily lead to unexpected behavior. However, it is the current behavior and so removing it might break some folks' working setups, potentially, so we must be careful. Previously I thought this was only done at build time, but this is a runtime behavior as well.

Curious what kind of output you see for your non-working scenarios.

**Comment by peckhams** [comment] 2022-11-18 13:33
Hi Matt,
Thanks for keeping this on your radar.  I will look into this as soon as I
get the chance.
However, this is a busy time (and pre-AGU), so it might not be until after
Thanksgiving.
Best regards,
Scott

**Comment by mattw-nws** [comment] 2023-08-22 16:21
@peckhams This one is getting long in the tooth and a few changes/additions have been made since it was originally reported. Is this still an issue? If not I'd like to close it.

**Comment by aaraney** [comment] 2024-07-16 13:38
@peckhams, there is a lot of overlap between this issue and #628. I think [this](https://github.com/NOAA-OWP/ngen/issues/628#issuecomment-2228684382) comment in that issue will solve your issue. I am going to close this in favor of this issue.

**Closed by aaraney** 2024-07-16 13:38 UTC
Labels: Compatibility Issues
