### ISSUE TITLE
Broken model run tests 

### ISSUE THREAD

**Issue by ZacharyWills** [NOAA-OWP/ngen#201] opened 2020-10-26 12:54 UTC
I think the gmake file wasn't updated somewhere along the way, so the new NGen.cpp fails to build. 

```
[ 97%] Building CXX object CMakeFiles/ngen.dir/src/NGen.cpp.o
714
/ngen/src/NGen.cpp: In function 'int main(int, char**)':
715
/ngen/src/NGen.cpp:241:55: error: 'time_step' was not declared in this scope
716
         catchment_outfiles[formulation_pair.first] << time_step << "," << current_timestamp << "," << output_str << std::endl;
717
                                                       ^~~~~~~~~
718
/ngen/src/NGen.cpp:241:55: note: suggested alternative: 'time_step_t'
719
         catchment_outfiles[formulation_pair.first] << time_step << "," << current_timestamp << "," << output_str << std::endl;
720
                                                       ^~~~~~~~~
721
                                                       time_step_t
722
gmake[3]: *** [CMakeFiles/ngen.dir/build.make:63: CMakeFiles/ngen.dir/src/NGen.cpp.o] Error 1
723
gmake[2]: *** [CMakeFiles/Makefile2:75: CMakeFiles/ngen.dir/all] Error 2
724
gmake[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/ngen.dir/rule] Error 2
725
gmake: *** [Makefile:175: ngen] Error 2
726
The command '/bin/sh -c cmake --build /ngen --target ngen' returned a non-zero code: 2
727
```

## Current behavior
Model runs are failing at the build, and need to be fixed.

## Expected behavior
Every time the action is triggered with new PRs the model should run

## Steps to replicate behavior (include URLs)

1. https://github.com/NOAA-OWP/ngen/runs/1299970026?check_suite_focus=true

## Screenshots
<img width="1674" alt="Screen Shot 2020-10-26 at 7 52 49 AM" src="https://user-images.githubusercontent.com/60660437/97174596-4eb95480-1760-11eb-9d3b-96f502bddb94.png">

**Comment by hellkite500** [comment] 2020-11-10 22:34
This happens because the CI container is building from `master` (see line 579 below):
<img width="1208" alt="Screen Shot 2020-11-10 at 4 31 49 PM" src="https://user-images.githubusercontent.com/5186647/98741511-6acd1080-2372-11eb-8b13-c437fed33a40.png">

So a previous bug in the driver snuck through the PR test because it was running the BASE, not the branch of the PR.  The next PR fails because it runs the base with the bug from the previous PR.

**Comment by hellkite500** [comment] 2020-11-24 14:02
#209 doesn't fix the root cause, which is the action runs master on ngen, not the PR.

**Comment by jdmattern-noaa** [comment] 2020-11-24 15:33
Right, it runs master, but now this variable is fixed in master, so we should not get the error that Zach pasted at the top whenever the CI clones and runs master.

**Comment by jdmattern-noaa** [comment] 2020-11-24 16:05
This test PR now passes the CI:
https://github.com/NOAA-OWP/ngen/pull/211

**Closed** 2021-05-07 23:17 UTC
Labels: CI/CD, bug
