### ISSUE TITLE
Ngen shows a NetCDF file closing error after finishing the run when using NetCDF forcing file

### ISSUE THREAD

**Issue by stcui007** [NOAA-OWP/ngen#818] opened 2024-05-09 16:10 UTC
This issue is created after today's discussion at the daily stand up. We agreed that there was a need to refresh people's mind about Issue 749, where there were some discussions and details about the issue already. The main point is that we need in our ngen code to close/destruct/cleanup all our files/objects before finishing.

https://github.com/NOAA-OWP/ngen/issues/749

As a reference, there is a rudimentary version that seems to fix the issue: https://github.com/stcui007/ngen/tree/I481_netcdf. Maybe a better design is needed.

## Steps to replicate behavior (include URLs)

1.

**Comment by PhilMiller** [comment] 2024-05-29 19:09
Duplicate of the earlier linked issue

**Comment by stcui007** [comment] 2024-05-30 13:55
Yes. The purpose was to remind people to not forget this issue as suggested
at a daily standup. Now we are on it, this is not needed.

**Closed** 2024-05-30 17:39 UTC
Labels: bug
