### ISSUE TITLE
Error while executing distributed version of ngen

### ISSUE THREAD

**Issue by pvbangalore** [NOAA-OWP/ngen#456] opened 2022-10-14 16:54 UTC
Short description explaining the high-level reason for the new issue.

## Current behavior
Program terminates with an exception in 'boost::wrapexcept<boost::property_tree::json_parser::json_parser_error>' due to unexpected value in partition_config.json (output.log attached has complete output)

## Expected behavior
Program should execute without any runtime errors.

## Steps to replicate behavior (include URLs)

Attached file (build_notes.log) shows all the steps to build and execute ngen with MPI

## Screenshots

[build_notes.txt](https://github.com/NOAA-OWP/ngen/files/9788477/build_notes.txt)
[output.log](https://github.com/NOAA-OWP/ngen/files/9788478/output.log)

**Comment by hellkite500** [comment] 2022-10-14 17:25
Can you add the partition file you generated? It looks like the issue is in parsing that file.

**Comment by pvbangalore** [comment] 2022-10-14 17:32
Here are the contents of the file partition_config.json:
`{
    "partitions":[
        {"id":0,
        "cat-ids":["cat-67"],
        "nex-ids":["nex-68"],
        "remote-connections":[]},
        {"id":1,
        "cat-ids":["cat-52"],
        "nex-ids":["nex-34"],
        "remote-connections":[]},
        {"id":2,
        "cat-ids":["cat-27"],
        "nex-ids":["nex-26"],
        "remote-connections":[]},
    ]
}`

**Comment by hellkite500** [comment] 2022-10-26 20:28
Ok, looking a little more at the input data used to build the partition file, there are only 3 catchments and 3 nexuses in the input data, but the partition generator tried making 4 partitions.  So I think the [serialization loop](https://github.com/NOAA-OWP/ngen/blob/25adad03d17466ce42fa63abe35079c3f239c311/src/partitionGenerator.cpp#L108) didn't terminate the strings correctly, as it adds a `,` after each partition up to `num_partitions` which is the number of requested partitions, not the not number of computed partitions. 

@stcui007 can you maybe look into catching this condition where the number of possible partitions is less than the number of requested partitions and make sure this serialization loop doesn't write invalid JSON?

**Comment by mattw-nws** [comment] 2022-11-14 14:43
Noting that this partition file also falls afoul of the empty `remote-connections` issue we identified, though that is something to be fixed in ngen rather than in partitionGenerator ... @hellkite500 : Fix for this issue can be pursued separately, yes?

**Comment by hellkite500** [comment] 2022-11-14 14:47
Yes, if using current HEAD that bug will show up. I should have a fix for that up shortly, though.

**Comment by stcui007** [comment] 2022-11-14 16:47
I was thinking about using 4 CPUs in the script for 3 catchments before
coming to Nels comment. That is probably the cause of the problem.

**Comment by mattw-nws** [comment] 2022-11-21 14:30
> Noting that this partition file also falls afoul of the empty remote-connections issue we identified...

See also #475

**Comment by mattw-nws** [comment] 2022-11-21 14:34
@pvbangalore Note that the fix in #474 basically prevents the creation of a partition file with more partitions than there are catchments in the catchment dataset, which it appears you did (3 catchments, 4 partitions). So you would continue to get this error with the same partition file, but that partitioning is not supported, basically. With only 3 catchments in the dataset, try creating only 2 partitions (and running only 2 processes), or try a larger dataset to run with > 3 partitions. If those configurations work, we can close this issue.

**Comment by mattw-nws** [comment] 2022-12-22 19:29
Believe this is fully fixed in #475... I just ran a config with zero remote nexuses in a partition and it succeeded. Will go ahead and close this but it can be reopened if the issue persists on the latest version.

**Closed by mattw-nws** 2022-12-22 19:29 UTC
Labels: bug, partitioner
